# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('date_start', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('date_finish', models.DateTimeField(verbose_name='Fecha de finalización')),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(null=True, upload_to='img/actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('date_start', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('date_finish', models.DateTimeField(verbose_name='Fecha de finalización')),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(null=True, upload_to='img/actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('date_start', models.DateTimeField(auto_now=True, verbose_name='Fecha última modificación')),
                ('date_finish', models.DateTimeField(null=True, verbose_name='Fecha de finalización')),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(null=True, upload_to='img/actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('date_start', models.DateTimeField(verbose_name='Fecha de realización')),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(null=True, upload_to='img/actividad')),
            ],
        ),
    ]
