# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conferencia',
            new_name='Otro',
        ),
    ]
